const designers: Designer[] = [
  {
    firstName: 'Aksel',
    lastName: 'Bender-Madsen',
    designerId: 'aksel_bender_madsen',
    birth: 1916,
    death: 2000,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/aksel_bender_madsen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/aksel_bender_madsen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Metropolitan',
        categories: ['chairs'],
        materials: ['wood', 'textile'],
        date: 1950,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/aksel_bender_madsen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood', 'textile'],
        date: 1955,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Arne',
    lastName: 'Jacobsen',
    designerId: 'arne_jacobsen',
    avatarSrc: '/media/archive/arne_jacobsen/avatar.jpg',
    heroSrc: '',
    birth: 1902,
    death: 1971,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    quote: 'The primary factor is... proportions.',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/arne_jacobsen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Ant',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1952,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/arne_jacobsen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Egg',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1958,
      },
      {
        productId: '3',
        thumbSrc: '/media/archive/arne_jacobsen/products/3/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Oksen',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1954,
      },
      {
        productId: '4',
        thumbSrc: '/media/archive/arne_jacobsen/products/4/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Oxford',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1952,
      },
      {
        productId: '5',
        thumbSrc: '/media/archive/arne_jacobsen/products/5/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Series 7',
        categories: ['chairs'],
        materials: ['leather', 'wood'],
        date: 1958,
      },
      {
        productId: '6',
        thumbSrc: '/media/archive/arne_jacobsen/products/6/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Series 3300',
        categories: ['sofa'],
        materials: ['leather', 'metal'],
        date: 1951,
      },
      {
        productId: '7',
        thumbSrc: '/media/archive/arne_jacobsen/products/7/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Super-Elliptical',
        categories: ['tables'],
        materials: ['wood', 'metal'],
        date: 1956,
      },
      {
        productId: '8',
        thumbSrc: '/media/archive/arne_jacobsen/products/8/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Swan',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1958,
      },
    ],
  },
  {
    firstName: 'Arne',
    lastName: 'Vodder',
    designerId: 'arne_vodder',
    birth: 1926,
    death: 2009,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/arne_vodder/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/arne_vodder/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1960,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/arne_vodder/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Number 62',
        categories: ['tables'],
        materials: ['wood'],
        date: 1955,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Bernt',
    lastName: 'Petersen',
    designerId: 'bernt_petersen',
    birth: 1937,
    death: 2017,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/bernt_petersen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/bernt_petersen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Rag Chair',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1955,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/bernt_petersen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['tables'],
        materials: ['wood'],
        date: 1959,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Bodil',
    lastName: 'Kjær',
    designerId: 'bodil_kjær',
    birth: 1932,
    death: null,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/bodil_kjær/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/bodil_kjær/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Executive Desk',
        categories: ['tables'],
        materials: ['wood', 'metal'],
        date: 1961,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/bodil_kjær/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Executive Drawer Unit',
        categories: ['storage'],
        materials: ['wood', 'metal'],
        date: 1961,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Børge',
    lastName: 'Mogensen',
    designerId: 'børge_mogensen',
    birth: 1914,
    death: 1972,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/børge_mogensen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/børge_mogensen/products/1/thumb.png',
        story: [],
        nickname: 'Huntsman Chair',
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'BM1106',
        categories: ['chairs'],
        materials: ['leather', 'wood'],
        date: 1955,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/børge_mogensen/products/2/thumb.png',
        story: [],
        nickname: 'Hunting Table',
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'BM1160',
        categories: ['tables'],
        materials: ['wood'],
        date: 1955,
      },
      {
        productId: '3',
        thumbSrc: '/media/archive/børge_mogensen/products/3/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model 3171',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1952,
      },
      {
        productId: '4',
        thumbSrc: '/media/archive/børge_mogensen/products/4/thumb.png',
        story: [],
        nickname: 'Coupé Sofa',
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model 2292',
        categories: ['sofa'],
        materials: ['leather', 'wood'],
        date: 1951,
      },
      {
        productId: '5',
        thumbSrc: '/media/archive/børge_mogensen/products/5/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model J39',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1956,
      },
      {
        productId: '6',
        thumbSrc: '/media/archive/børge_mogensen/products/6/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Spanish Chair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1956,
      },
      {
        productId: '7',
        thumbSrc: '/media/archive/børge_mogensen/products/7/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Spoke-Back Sofa',
        categories: ['sofa'],
        materials: ['wood', 'leather'],
        date: 1952,
      },
      {
        productId: '8',
        thumbSrc: '/media/archive/børge_mogensen/products/8/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Wing Chair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1954,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Edvard',
    lastName: 'Kindt-Larsen',
    designerId: 'edvard_kindt_larsen',
    birth: 1901,
    death: 1982,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/edvard_kindt_larsen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/edvard_kindt_larsen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1957,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/edvard_kindt_larsen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        date: 1957,
        categories: ['tables'],
        materials: ['wood'],
      },
    ],
    quote: null,
  },
  {
    firstName: 'Ejner',
    lastName: 'Larsen',
    designerId: 'ejner_larsen',
    birth: 1917,
    death: 1987,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/ejner_larsen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/ejner_larsen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1961,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/ejner_larsen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1964,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Erik',
    lastName: 'Ole Jørgensen',
    designerId: 'erik_ole_jørgensen',
    birth: 1925,
    death: 2002,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/erik_ole_jørgensen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/erik_ole_jørgensen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model J361',
        categories: ['chairs'],
        materials: ['metal', 'textile'],
        date: 1960,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/erik_ole_jørgensen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['metal', 'textile'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Finn',
    lastName: 'Juhl',
    designerId: 'finn_juhl',
    birth: 1912,
    death: 1989,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/finn_juhl/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/finn_juhl/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Chieftain Chair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1949,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/finn_juhl/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Grasshopper Chair',
        categories: ['chairs'],
        materials: ['wood', 'textile'],
        date: 1938,
      },
      {
        productId: '3',
        thumbSrc: '/media/archive/finn_juhl/products/3/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model 46',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1946,
      },
      {
        productId: '4',
        thumbSrc: '/media/archive/finn_juhl/products/4/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Panel System',
        categories: ['storage'],
        materials: [],
        date: 1949,
      },
      {
        productId: '5',
        thumbSrc: '/media/archive/finn_juhl/products/5/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Pelican Chair',
        categories: ['chairs'],
        materials: [],
        date: 1940,
      },
      {
        productId: '6',
        thumbSrc: '/media/archive/finn_juhl/products/6/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood', 'metal'],
        date: 1953,
      },
      {
        productId: '7',
        thumbSrc: '/media/archive/finn_juhl/products/7/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['storage'],
        materials: [],
        date: 1953,
      },
      {
        productId: '8',
        thumbSrc: '/media/archive/finn_juhl/products/8/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['tables'],
        materials: ['wood'],
        date: 1953,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Frits',
    lastName: 'Henningsen',
    designerId: 'frits_henningsen',
    birth: 1889,
    death: 1965,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/frits_henningsen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/frits_henningsen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood'],
        date: 1960,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/frits_henningsen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['storage'],
        materials: ['wood'],
        date: 1950,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Grete',
    lastName: 'Jalk',
    designerId: 'grete_jalk',
    birth: 1920,
    death: 2006,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/grete_jalk/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/grete_jalk/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'GJ 118',
        date: 1958,
        categories: ['chairs'],
        materials: ['wood'],
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/grete_jalk/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'GJ Bow',
        date: 1963,
        categories: ['chairs'],
        materials: ['wood'],
      },
    ],
    quote: null,
  },
  {
    firstName: 'Hans',
    lastName: 'Bølling',
    designerId: 'hans_bølling',
    birth: 1931,
    death: null,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/hans_bølling/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/hans_bølling/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Duck & Duckling',
        categories: ['accessories'],
        materials: ['wood'],
        date: 1959,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/hans_bølling/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Mermaid',
        categories: ['accessories'],
        materials: ['wood'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Hans',
    lastName: 'Olsen',
    designerId: 'hans_olsen',
    birth: 1919,
    death: 1992,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/hans_olsen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/hans_olsen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Bikini Chair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1960,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/hans_olsen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood', 'textile'],
        date: 1955,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Hans',
    lastName: 'Wegner',
    designerId: 'hans_wegner',
    avatarSrc: '/media/archive/hans_wegner/avatar.jpg',
    heroSrc: '/media/archive/hans_wegner/hero.jpg',
    birth: 1914,
    death: 2007,
    birthPlace: 'Tønder, Prussia, German Empire',
    restingPlace: 'Mariebjerg Cemetery',
    introductoryParagraph:
      'Among Danish furniture designers, Hans J. Wegner is considered one of the most creative, innovative and prolific. Often referred to as the master of the chair, Wegner created almost 500 in his lifetime – many of them considered masterpieces. His iconic Wishbone Chair is probably the most well-known and has been in continuous production since 1950.',
    education: ['Teknologisk Institut', 'Danmarks Designskole'],
    spouses: [{ name: 'Inga Helbo', info: 'm. 1940' }],
    children: ['Marianne Wegner Sørensen', 'Eva Wegner'],
    awards: [
      { name: 'Lunning Prize', date: 1951 },
      { name: 'Grand prix of the Milan Triennial IX', date: 1951 },
      { name: 'Gold medal of the Milan Triennial', date: 1956 },
      { name: 'Eckersberg Medal', date: 1956 },
      { name: 'Citation of Merit from the Pratt institute', date: 1961 },
      { name: 'Prince Eugen Medal', date: 1961 },
      { name: 'AID design award', date: 1961 },
      { name: 'Royal Designers for Industry', date: 1969 },
      { name: 'Diploma di collaborazione Triennale di Milano', date: 1973 },
      { name: 'Danish Furniture Prize', date: 1980 },
      { name: 'C. F. Hansen Medal', date: 1982 },
      { name: 'Danish Design Council’s Annual Prize', date: 1987 },
      { name: '8th International Design Award', date: 1997 },
    ],
    quote:
      'If only you could design just <em>one</em> <em>good</em> <em>chair</em> in your life – but, you simply cannot.',
    bio: [
      {
        header: 'Beginnings',
        date: 1914,
        text: [
          'Wegner was born to cobbler Peter Mathiesen Wegner and Nicoline Lausen on Smedegade 12 in Tønder. At an early age, Wegner shown interest in craft and could draw and create paper cuttings before he learned to walk. At home, Wegner was drawn to woodcarving and created wood sculptures based on Royal Copenhagen figurines he saw at the Tønder Museum.',
          'At the age of 14, he worked as a child apprentice to master cabinetmaker H. F. Stahlberg. He soon discovered he had a feeling for wood and developed an affinity towards the material. At the age of 15, he made his first chair. Finishing his apprenticeship at 17, he crafted a lady’s desk as part of his journeyman’s test and remained employed in the workshop before joining the army.',
        ],
        media: [
          {
            type: 'img',
            src: '/media/archive/hans_wegner/bio/1_young.jpg',
            caption:
              'Hans Wegner (3rd from the left) at the age of 14 during an apprenticeship with H.F. Stahlberg',
          },
          {
            type: 'img',
            src: '/media/archive/hans_wegner/bio/2_birthplace.jpg',
            caption: 'The street of Wegner’s childhood home, circa 1915',
          },
        ],
      },
      {
        header: 'Aarhus',
        date: 1938,
        text: [
          'In 1938, Wegner took a one-year leave from his studies to work on the Aarhus City Hall project on the recommendation of his teacher. Arne Jacobsen and Erik Møller had won a bid to design the Aarhus City Hall and employed Wegner to create the furniture. However, World War II caused delays in the City Hall project and he was first assigned to work on the Nyborg Public Library under Møller and Flemming Lassen. Today, the library displays early photos of Wegner’s contributions to the library as well as a website dedicated to the historic design. While the library was well-received and Møller and Lassen were awarded the Eckersberg Medal, Wegner’s contributions weren’t as widely publicized at the time.',
          'From 1939 to 1942, Wegner worked on the Aarhus City Hall project and was responsible for all the furnishings. Wegner began working on three lines of modular office furniture for Planmøbler while working on the City Hall. Some of the Planmøbler furniture was used in the office wings of the City Hall.',
        ],
        media: [
          {
            type: 'img',
            src: '/media/archive/hans_wegner/bio/3_aarhus1.jpg',
            caption:
              'H. F. Stahlberg’s workshop where Wegner was employed, circa 1905',
          },
          {
            type: 'img',
            src: '/media/archive/hans_wegner/bio/4_sketch1.jpg',
            caption:
              'A 1950 drawing for the Wishbone Chair, which soon became Wegner’s best-selling and most famous piece of furniture',
          },
          {
            type: 'img',
            src: '/media/archive/hans_wegner/bio/5_sketch2.jpg',
            caption: 'Sketches for the Flag Halyard Chair',
          },
        ],
      },
      {
        header: 'International Success',
        date: 1946,
        text: [
          'Wegner returned to Copenhagen in 1946 where he accepted a teaching position at the Danish School of Arts and Crafts at <a href="/">Mølgaard-Nielsen</a>’s suggestion. Wegner also worked for Palle Suenson’s studio while teaching, where he was primarily responsible for renovating and designing furniture for the M/S Venus, a ship which had been damaged by the Germans during the occupation.',
        ],
        media: [
          {
            type: 'img',
            src: '/media/archive/hans_wegner/bio/6_return_to_copenhagen_and_international_success.jpg',
            caption:
              'Chatting with fellow designer <a href="/">Charles Eames</a> at the opening of the 1959 Wegner retrospective at Georg Jensen in New York.',
          },
        ],
      },
      {
        header: 'Decline in Popularity',
        date: 1960,
        text: [
          'US imports of Wegner’s furniture declined in the late 1960s due to an ill-fated deal with <a href="/">Georg Jensen</a>, Inc (the New York agency for Georg Jensen and a premier retailer for Danish home goods). In this agreement, Salesco gave Georg Jensen exclusive distribution rights within the United States. Georg Jensen added a hefty premium on all of Wegner’s furniture which frustrated interior designers who balked at paying 3–4 times the retail prices in Denmark. When Georg Jensen shuttered in 1968, the US was left without a distributor for Salesco’s five manufacturers. Johannes Hansen was not a member of the organization and was unaffected by this.',
        ],
        media: [
          {
            type: 'img',
            src: '/media/archive/hans_wegner/bio/7_supplier_issues_and_decline_in_popularity.jpg',
          },
        ],
      },
      {
        header: 'Later Years',
        date: 1968,
        text: [
          'After the fallout with Salesco, Wegner became more attached to <a href="/">PP Møbler</a>. PP Møbler was a supplier to <a href="/">A.P. Stolen</a> but didn’t produce furniture under its own name. From 1962 to 1968, Wegner used PP Møbler workshop to create prototypes and experiments; when successful, the designs would go into production with other manufacturers like Getama and A.P. Stolen. In 1969, he urged the company to produce under its own brand name and his first chair especially for PP Møbler (PP201). Wegner also designed their logo. As Wegner’s other manufacturers closed down, he moved production of many pieces originally designed for Andreas Tuck, A.P. Stolen, and Johannes Hansen to PP Møbler.',
        ],
        media: [
          {
            type: 'img',
            src: '/media/archive/hans_wegner/bio/8_later_years_and_revival.jpg',
          },
        ],
      },
      {
        header: 'Legacy',
        date: 1993,
        text: [
          'As Wegner got older, his health started declining and he withdrew from work. Wegner retired in 1993 and his daughter Marianne took over his studio.',
          '<blockquote><p>Towards the end of the 1980s, I could feel that my father’s energy level was faltering… but I was there to help out. I took on more and more tasks along the way. He continued to draw some furniture until 1993, but after that, he couldn’t really concentrate on the work anymore and he also had trouble walking down the stairs to the drawing room.</q> He was placed in a nursing home in 2001 and started using a wheelchair.</p></blockquote><figcaption>&mdash; Marianne Wegner</figcaption>',
          'On January 26, 2007, Wegner passed away at the age of 92. In Wegner’s own lifetime he was able to witness a surge of renewed interest in his work. PP Møbler and Marianne Wegner worked together to create an engraved oak headstone for his gravesite at Mariebjerg Cemetery in Gentofte.',
        ],
        media: [
          {
            type: 'img',
            src: '/media/archive/hans_wegner/bio/9_retirement_and_legacy.jpg',
            caption:
              'Lounging in another of his large and laid-back chairs, the Ox, designed in 1960. <q>Although its huge, bulging body stands in contrast to the <a href="/">Flag Halyard Chair</a>, the <a href="/">Ox</a> presents a similarly radically innovative design</q>, notes Christian Holmsted Olesen in his book – ”Hans J. Wegner: Just One Good Chair.“',
          },
        ],
      },
    ],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/hans_wegner/products/1/thumb.png',
        story: [
          'With a form that is uniquely its own, the iconic CH24 Wishbone Chair by Hans J. Wegner holds a special place in the world of modern design.',
          'When designing the CH24, Wegner chose to combine the back and armrest into a single piece. To give stability to the steam-bent top and ensure comfortable support, Wegner developed the characteristic Y-shaped back that the Wishbone Chair is named after.',
          [
            {
              type: 'img',
              src: '/media/archive/hans_wegner/products/1/2.jpg',
            },
            {
              type: 'img',
              src: '/media/archive/hans_wegner/products/1/1.jpg',
            },
            {
              type: 'vid',
              src: '/media/archive/hans_wegner/products/1/3.mp4',
            },
          ],
          'More than 100 steps are required to manufacture each Wishbone Chair, most of which are carried out by hand. The hand-woven seat alone takes a skilled craftsman about an hour to create, using approximately 120 meters of paper cord, the impressive durability and stability of which makes the chair both strong and long-lasting. The Wishbone Chair offers comfort and stability as well as satisfying aesthetic desires for distinctive, elegant form.',
          'Over time, the Wishbone Chair has gained recognition as the ideal chair, capturing the essence of modern Danish design.',
          [
            {
              type: 'img',
              src: '/media/archive/hans_wegner/products/1/4.jpg',
            },
          ],
        ],
        nickname: 'Wishbone Chair',
        brand: 'Carl Hansen & Søn',
        productURL: 'https://www.carlhansen.com/en/collection/chairs/ch24',
        dimensionsCm: {
          w: 55,
          h: 76,
          d: 51,
        },
        model: 'CH24',
        categories: ['chairs'],
        materials: ['wood', 'textile'],
        date: 1949,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/hans_wegner/products/2/thumb.png',
        story: [],
        nickname: 'Chinese Chair',
        brand: 'PP Møbler',
        productURL: null,
        dimensionsCm: null,
        model: 'pp56',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1952,
      },
      {
        productId: '3',
        thumbSrc: '/media/archive/hans_wegner/products/3/thumb.png',
        story: [],
        nickname: null,
        brand: 'PP Møbler',
        productURL: null,
        dimensionsCm: null,
        model: 'pp112',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1978,
      },
      {
        productId: '4',
        thumbSrc: '/media/archive/hans_wegner/products/4/thumb.png',
        story: [],
        nickname: null,
        brand: 'PP Møbler',
        productURL: null,
        dimensionsCm: null,
        model: 'pp201',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1952,
      },
      {
        productId: '5',
        thumbSrc: '/media/archive/hans_wegner/products/5/thumb.png',
        story: [],
        nickname: 'Chair',
        brand: 'PP Møbler',
        productURL: null,
        dimensionsCm: null,
        model: 'pp501',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1949,
      },
      {
        productId: '6',
        thumbSrc: '/media/archive/hans_wegner/products/6/thumb.png',
        story: [],
        nickname: 'Cow Horn Chair',
        brand: 'PP Møbler',
        productURL: null,
        dimensionsCm: null,
        model: 'pp505',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1952,
      },
      {
        productId: '7',
        thumbSrc: '/media/archive/hans_wegner/products/7/thumb.png',
        story: [],
        nickname: 'Bull Chair',
        brand: 'PP Møbler',
        productURL: null,
        dimensionsCm: null,
        model: 'pp518',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1952,
      },
      {
        productId: '8',
        thumbSrc: '/media/archive/hans_wegner/products/8/thumb.png',
        story: [],
        nickname: 'Peacock Chair',
        brand: 'PP Møbler',
        productURL: null,
        dimensionsCm: null,
        model: 'pp550',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1947,
      },
    ],
  },
  {
    firstName: 'Helge',
    lastName: 'Jensen',
    designerId: 'helge_jensen',
    birth: 1917,
    death: 1987,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/helge_jensen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/helge_jensen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood'],
        date: 1955,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/helge_jensen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Racket Chair',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1955,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Ib',
    lastName: 'Kofod-Larsen',
    designerId: 'ib_kofod_larsen',
    birth: 1916,
    death: 2016,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/ib_kofod_larsen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/ib_kofod_larsen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Seal Chair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1950,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/ib_kofod_larsen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Shell Chair',
        categories: ['chairs'],
        materials: ['wood', 'textile'],
        date: 1950,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Jacob',
    lastName: 'Kjær',
    designerId: 'jacob_kjær',
    birth: 1896,
    death: 1957,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/jacob_kjær/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/jacob_kjær/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'FN Chair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1958,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/jacob_kjær/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1957,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Jens',
    lastName: 'Quistgaard',
    designerId: 'jens_quistgaard',
    birth: 1919,
    death: 2008,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/jens_quistgaard/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/jens_quistgaard/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['accessories'],
        materials: ['wood'],
        date: 1958,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/jens_quistgaard/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Safari Chair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1965,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Jens',
    lastName: 'Risom',
    designerId: 'jens_risom',
    birth: 1916,
    death: 2016,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/jens_risom/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/jens_risom/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model 654W',
        categories: ['chairs'],
        materials: ['wood', 'textile'],
        date: 1943,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/jens_risom/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model 666C',
        categories: ['chairs'],
        materials: ['wood', 'textile'],
        date: 1943,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Jørgen',
    lastName: 'Gammelgaard',
    designerId: 'jørgen_gammelgaard',
    birth: 1938,
    death: 1991,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/jørgen_gammelgaard/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/jørgen_gammelgaard/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model EJ20',
        categories: ['sofa'],
        materials: ['wood', 'textile'],
        date: 1968,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/jørgen_gammelgaard/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1970,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Jørgen',
    lastName: 'Kastholm',
    designerId: 'jørgen_kastholm',
    birth: 1931,
    death: 2007,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/jørgen_kastholm/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/jørgen_kastholm/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Desk',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1956,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/jørgen_kastholm/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'FK87 Grasshopper',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1968,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Kaare',
    lastName: 'Klint',
    designerId: 'kaare_klint',
    birth: 1888,
    death: 1954,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/kaare_klint/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/kaare_klint/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Card Chair',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1934,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/kaare_klint/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Church Chair',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1936,
      },
      {
        productId: '3',
        thumbSrc: '/media/archive/kaare_klint/products/3/thumb.png',
        story: [],
        nickname: 'Propeller Stool',
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'KK87830',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1930,
      },
      {
        productId: '4',
        thumbSrc: '/media/archive/kaare_klint/products/4/thumb.png',
        story: [],
        nickname: 'Faaborg Chair',
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'KK96620',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1914,
      },
      {
        productId: '5',
        thumbSrc: '/media/archive/kaare_klint/products/5/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood'],
        date: 1933,
      },
      {
        productId: '6',
        thumbSrc: '/media/archive/kaare_klint/products/6/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood'],
        date: 1950,
      },
      {
        productId: '7',
        thumbSrc: '/media/archive/kaare_klint/products/7/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Ravenna Chair',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1948,
      },
      {
        productId: '8',
        thumbSrc: '/media/archive/kaare_klint/products/8/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Safari Chair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1933,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Kai',
    lastName: 'Kristiansen',
    designerId: 'kai_kristiansen',
    birth: 1929,
    death: null,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/kai_kristiansen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/kai_kristiansen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Kompass Chair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1960,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/kai_kristiansen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model 42',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Kay',
    lastName: 'Bojesen',
    designerId: 'kay_bojesen',
    avatarSrc: '/media/archive/kay_bojesen/avatar.jpg',
    heroSrc: '/media/archive/kay_bojesen/hero.jpg',
    birth: 1886,
    death: 1958,
    birthPlace: 'Copenhagen, Denmark',
    restingPlace: 'Hørsholm Kirkegård, Hørsholm, Denmark',
    introductoryParagraph:
      'Silversmith and designer Kay Bojesen had a very special talent. He was able to bring wood to life, and he became world-famous for creating wooden toys that had soul and an impish sense of humour. With more than 2000 pieces to his name, Kay Bojesen was one of Denmark‘s most prolific artisans in the 20th century. He is best known for his playful and cheerful monkeys, royal life guards and other wooden toys, but his wide-ranging production also includes jewellery, cutlery, teapots and silver goblets.',
    education: ['George Jensen, Denmark', 'Schwabisch Gmund, Germany'],
    spouses: [{ name: 'Erna Bojesen', info: 'm. 1911' }],
    children: ['Otto Bojesen'],
    awards: [{ name: 'Milan Triennale Grand Prix', date: 1922 }],
    quote:
      'An item must function properly, be nice to hold and a pleasure to look at… Above all, it must have a <em>soul.</em>',
    bio: [
      {
        header: 'Early Life',
        date: 1886,
        media: [
          {
            type: 'img',
            src: '/media/archive/kay_bojesen/bio/1.jpg',
            caption: 'Kay Bojesen in front of his shop in Copenhagen',
          },
        ],
        text: [
          'Kay Bojesen was born in 1886 and grew up in a creative home. His father was Ernst Bojesen, co-founder of the publishing house Det Nordiske Forlag, which later became known as Gyldendal.',
        ],
      },
      {
        header: 'Education',
        date: 1910,
        media: [
          {
            type: 'img',
            src: '/media/archive/kay_bojesen/bio/2.jpg',
            caption: 'Sketches for the Monkey',
          },
        ],
        text: [
          'Young Kay started his training in a grocery store, but as luck has it, he was offered an apprenticeship at Georg Jensen’s newly established silversmith. The time called for Art Nouveau rules with hammered surfaces, but Kay’s eye for form and function made him responsive to new currents. Kay Bojesen became a great advocate of functionalism, and he was fascinated by the clean, smooth surfaces of the silver, where the material and it’s reflections were decoration in itself.',
        ],
      },
      {
        header: 'Grand Prix',
        date: 1938,
        media: [
          {
            type: 'img',
            src: '/media/archive/kay_bojesen/bio/3.jpg',
          },
          {
            type: 'img',
            src: '/media/archive/kay_bojesen/bio/4.jpg',
          },
        ],
        text: [
          'In 1938, Kay Bojesen presented the ultimate cutlery series in silver, crafted out of the belief that cutlery was a tool that shouldn’t steal the picture at a table setting. All pieces of cutlery were crafted with soft and harmonious shapes in order to fit the human hand and mouth. In 1951, Kay’s silverware took the first prize at the world exhibition in Milan, and was therefore named “Grand Prix”.',
        ],
      },
      {
        header: 'Royal Purveyor',
        date: 1952,
        media: [
          {
            type: 'img',
            src: '/media/archive/kay_bojesen/bio/5.jpg',
          },
        ],
        text: [
          'In 1952, Kay Bojesen was appointed Purveyor to His Majesty the King of Denmark – “for long and regular trade with the Court”. But not just crowned heads feast on Grand Prix. The cutlery is used to set the tables in Danish Embassy residences around the world, and therefore pride itself with the rare title “Embassy-Cutlery”.',
        ],
      },
      {
        header: 'Legacy',
        date: 1958,
        media: [
          {
            type: 'img',
            src: '/media/archive/kay_bojesen/bio/6.jpg',
          },
        ],
        text: [
          'Bojesen died August 28, 1958, at the age of 72. His shop in Copenhagen, which he founded in 1932, operated until the nineteen-eighties. Following his death it was continued by his widow Erna Bojesen until her death in 1986.',

          'Bojesen was an honorary member of the National Association of Danish Arts and Crafts, and was recognized for his toys by the Danish National Committee of the OEMP (World Organisation for Early Childhood Education).',
        ],
      },
    ],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/kay_bojesen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: 'Rosendahl',
        productURL: null,
        dimensionsCm: null,
        model: 'Bear',
        categories: ['accessories'],
        materials: ['wood'],
        date: 1952,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/kay_bojesen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: 'Rosendahl',
        productURL: null,
        dimensionsCm: null,
        model: 'Dog',
        categories: ['accessories'],
        materials: ['wood'],
        date: 1934,
      },
      {
        productId: '3',
        thumbSrc: '/media/archive/kay_bojesen/products/3/thumb.png',
        story: [],
        nickname: null,
        brand: 'Rosendahl',
        productURL: null,
        dimensionsCm: null,
        model: 'Elephant',
        categories: ['accessories'],
        materials: ['wood'],
        date: 1953,
      },
      {
        productId: '4',
        thumbSrc: '/media/archive/kay_bojesen/products/4/thumb.png',
        story: [],
        nickname: null,
        brand: 'Rosendahl',
        productURL: null,
        dimensionsCm: null,
        model: 'Hippo',
        categories: ['accessories'],
        materials: ['wood'],
        date: 1955,
      },
      {
        productId: '5',
        thumbSrc: '/media/archive/kay_bojesen/products/5/thumb.png',
        story: [],
        nickname: null,
        brand: 'Rosendahl',
        productURL: null,
        dimensionsCm: null,
        model: 'Horse',
        categories: ['accessories'],
        materials: ['wood'],
        date: 1930,
      },
      {
        productId: '6',
        thumbSrc: '/media/archive/kay_bojesen/products/6/thumb.png',
        story: [
          'Kay Bojesen’s Monkey comprises 31 parts and is made of limba wood and sustainable teak. Every single member of the monkey family is produced in Denmark, and is absolutely unique. It’s a beloved classic of Scandinavian design.',
          'This monkey is made of teak and legally harvested limba wood complies with the European Union Timber Regulation (EUTR). The plantation teak guarantees responsible harvesting and better living conditions for locals living close to the plantations.',
          [{ src: '/media/archive/kay_bojesen/products/6/1.png', type: 'img' }],
          'Bojesen’s monkey with its mischievous look and light coloured belly has transformed kids’ rooms into jungles and sparked dreams of far-away places since 1951. It has a permanent role on Danish television as the mascot of wildlife programs and as a prize in quiz shows. Every monkey consists of 31 wooden parts and is crafted by hand in Denmark. Due to slight variation in shade and wood grain, the monkeys have a unique and charming personality.',
          [
            { src: '/media/archive/kay_bojesen/products/6/2.jpg', type: 'img' },
            { src: '/media/archive/kay_bojesen/products/6/3.jpg', type: 'img' },
            { src: '/media/archive/kay_bojesen/products/6/4.jpg', type: 'img' },
          ],
          'Over time, exposure to the light and the air may change the subtle shades of the teak to a more consistent, warm golden brown tone. However, every single Kay Bojesen Monkey will retain its absolutely unique personality.',
          [{ src: '/media/archive/kay_bojesen/products/6/5.png', type: 'img' }],
        ],
        nickname: null,
        brand: 'Rosendahl',
        productURL:
          'https://www.kaybojesen-denmark.com/shop/collection/monkey/p-8440/monkey-mini-teak-limba',
        dimensionsCm: {
          d: 9.45,
          h: 20,
          w: 17,
        },
        model: 'Monkey',
        categories: ['accessories'],
        materials: ['wood'],
        date: 1951,
      },
      {
        productId: '7',
        thumbSrc: '/media/archive/kay_bojesen/products/7/thumb.png',
        story: [],
        nickname: null,
        brand: 'Rosendahl',
        productURL: null,
        dimensionsCm: null,
        model: 'Pair of Sparrows',
        categories: ['accessories'],
        materials: ['wood'],
        date: 1950,
      },
      {
        productId: '8',
        thumbSrc: '/media/archive/kay_bojesen/products/8/thumb.png',
        story: [],
        nickname: null,
        brand: 'Rosendahl',
        productURL: null,
        dimensionsCm: null,
        model: 'Royal Guardsmen',
        categories: ['accessories'],
        materials: ['wood'],
        date: 1942,
      },
    ],
  },
  {
    firstName: 'Kurt',
    lastName: 'Østervig',
    designerId: 'kurt_østervig',
    birth: 1912,
    death: 1986,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/kurt_østervig/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/kurt_østervig/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood'],
        date: 1960,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/kurt_østervig/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['storage'],
        materials: ['wood'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Mogens',
    lastName: 'Koch',
    designerId: 'mogens_koch',
    birth: 1914,
    death: 2007,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/mogens_koch/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/mogens_koch/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Additional Chairs',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1960,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/mogens_koch/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'MK9920',
        categories: ['chairs'],
        materials: ['wood', 'textile'],
        date: 1932,
      },
      {
        productId: '3',
        thumbSrc: '/media/archive/mogens_koch/products/3/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'MK88360',
        categories: ['storage'],
        materials: ['wood'],
        date: 1932,
      },
      {
        productId: '4',
        thumbSrc: '/media/archive/mogens_koch/products/4/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'MK98400',
        categories: ['storage'],
        materials: ['wood'],
        date: 1932,
      },
      {
        productId: '5',
        thumbSrc: '/media/archive/mogens_koch/products/5/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'MK98860',
        categories: ['tables'],
        materials: ['wood'],
        date: 1960,
      },
      {
        productId: '6',
        thumbSrc: '/media/archive/mogens_koch/products/6/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model 52',
        categories: ['sofa'],
        materials: ['leather'],
        date: 1936,
      },
      {
        productId: '7',
        thumbSrc: '/media/archive/mogens_koch/products/7/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['storage'],
        materials: ['wood'],
        date: 1960,
      },
      {
        productId: '8',
        thumbSrc: '/media/archive/mogens_koch/products/8/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Wingback Chair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1930,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Mogens',
    lastName: 'Lassen',
    designerId: 'mogens_lassen',
    birth: 1901,
    death: 1987,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/mogens_lassen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/mogens_lassen/products/1/thumb.png',
        story: [],
        nickname: 'Egyptian Table',
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'ML10097',
        categories: ['tables'],
        materials: ['wood'],
        date: 1961,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/mogens_lassen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood', 'textile'],
        date: 1961,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Nanna',
    lastName: 'Ditzel',
    designerId: 'nanna_ditzel',
    birth: 1925,
    death: 2003,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/nanna_ditzel/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/nanna_ditzel/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Hanging Egg',
        categories: ['chairs'],
        materials: ['textile'],
        date: 1959,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/nanna_ditzel/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Madame Chair',
        categories: ['chairs'],
        materials: ['textile'],
        date: 1965,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Ole',
    lastName: 'Wanscher',
    designerId: 'ole_wanscher',
    birth: 1903,
    death: 1985,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/ole_wanscher/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/ole_wanscher/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Colonial Armchair',
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1949,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/ole_wanscher/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Colonial Sofa',
        categories: ['sofa'],
        materials: ['wood', 'leather'],
        date: 1964,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Orla',
    lastName: 'Mølgaard-Nielsen',
    designerId: 'orla_mølgaard_nielsen',
    birth: 1907,
    death: 1993,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/orla_mølgaard_nielsen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/orla_mølgaard_nielsen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'AX Chair',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1960,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/orla_mølgaard_nielsen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood', 'leather'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Peder',
    lastName: 'Moos',
    designerId: 'peder_moos',
    birth: 1906,
    death: 1991,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/peder_moos/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/peder_moos/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['tables'],
        materials: ['wood'],
        date: 1949,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/peder_moos/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['wood'],
        date: 1949,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Peter',
    lastName: 'Hvidt',
    designerId: 'peter_hvidt',
    birth: 1916,
    death: 1986,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/peter_hvidt/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/peter_hvidt/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['storage'],
        materials: ['wood'],
        date: 1951,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/peter_hvidt/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'X Chair',
        categories: ['chairs'],
        materials: ['wood'],
        date: 1950,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Poul',
    lastName: 'Henningsen',
    designerId: 'poul_henningsen',
    avatarSrc: '/media/archive/poul_henningsen/avatar.jpg',
    heroSrc: '',
    birth: 1894,
    death: 1967,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    quote:
      'The technician should never forget that he is an artist, the artist never that he is a technician.',
    bio: [],
    works: [],
  },
  {
    firstName: 'Poul',
    lastName: 'Kjærholm',
    designerId: 'poul_kjærholm',
    avatarSrc: '/media/archive/poul_kjærholm/avatar.jpg',
    heroSrc: '',
    birth: 1929,
    death: 1980,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    quote:
      'Steel’s constructive potential is not the only thing that interests me; the refraction of light on its surface is an important part of my artistic work. I consider steel a material with the same artistic merit as wood and leather.',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/poul_kjærholm/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'PK1',
        categories: ['chairs'],
        materials: ['metal', 'textile'],
        date: 1955,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/poul_kjærholm/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'PK22',
        categories: ['chairs'],
        materials: ['metal', 'leather'],
        date: 1956,
      },
      {
        productId: '3',
        thumbSrc: '/media/archive/poul_kjærholm/products/3/thumb.png',
        story: [],
        nickname: 'Hammock Chair',
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'PK24',
        categories: ['chairs'],
        materials: ['metal', 'textile'],
        date: 1965,
      },
      {
        productId: '4',
        thumbSrc: '/media/archive/poul_kjærholm/products/4/thumb.png',
        story: [],
        nickname: 'Element Chair',
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'PK25',
        categories: ['chairs'],
        materials: ['metal', 'leather'],
        date: 1951,
      },
      {
        productId: '5',
        thumbSrc: '/media/archive/poul_kjærholm/products/5/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'PK31',
        categories: ['chairs'],
        materials: ['metal', 'leather'],
        date: 1960,
      },
      {
        productId: '6',
        thumbSrc: '/media/archive/poul_kjærholm/products/6/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'PK52',
        categories: ['tables'],
        materials: ['metal', 'leather'],
        date: 1955,
      },
      {
        productId: '7',
        thumbSrc: '/media/archive/poul_kjærholm/products/7/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'PK58',
        categories: ['tables'],
        materials: ['metal', 'leather'],
        date: 1960,
      },
      {
        productId: '8',
        thumbSrc: '/media/archive/poul_kjærholm/products/8/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'PK80',
        categories: ['chairs'],
        materials: ['leather', 'wood'],
        date: 1957,
      },
    ],
  },
  {
    firstName: 'Poul',
    lastName: 'Volther',
    designerId: 'poul_volther',
    birth: 1923,
    death: 2001,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/poul_volther/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/poul_volther/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'EJ 5 Corona',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1961,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/poul_volther/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'EJ 5-F',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1961,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Preben',
    lastName: 'Fabricius',
    designerId: 'preben_fabricius',
    birth: 1931,
    death: 1984,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/preben_fabricius/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/preben_fabricius/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Model 710',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1959,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/preben_fabricius/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Tulip',
        categories: ['chairs'],
        materials: ['leather', 'metal'],
        date: 1961,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Rigmor',
    lastName: 'Andersen',
    designerId: 'rigmor_andersen',
    birth: 1903,
    death: 1995,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/rigmor_andersen/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/rigmor_andersen/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['chairs'],
        materials: ['leather', 'wood'],
        date: 1960,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/rigmor_andersen/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: null,
        categories: ['tables'],
        materials: ['wood'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Verner',
    lastName: 'Panton',
    designerId: 'verner_panton',
    birth: 1926,
    death: 1998,
    birthPlace: null,
    restingPlace: null,
    introductoryParagraph: null,
    education: [],
    spouses: [],
    children: [],
    awards: [],
    avatarSrc: '/media/archive/verner_panton/avatar.jpg',
    heroSrc: '',
    bio: [],
    works: [
      {
        productId: '1',
        thumbSrc: '/media/archive/verner_panton/products/1/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Amoebe',
        categories: ['chairs'],
        materials: ['textile'],
        date: 1970,
      },
      {
        productId: '2',
        thumbSrc: '/media/archive/verner_panton/products/2/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Barboy',
        categories: ['accessories'],
        materials: ['plastic'],
        date: 1964,
      },
      {
        productId: '3',
        thumbSrc: '/media/archive/verner_panton/products/3/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'C1',
        categories: ['chairs'],
        materials: ['textile', 'metal'],
        date: 1964,
      },
      {
        productId: '4',
        thumbSrc: '/media/archive/verner_panton/products/4/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Cone',
        categories: ['chairs'],
        materials: ['textile', 'metal'],
        date: 1959,
      },
      {
        productId: '5',
        thumbSrc: '/media/archive/verner_panton/products/5/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Heart',
        categories: ['chairs'],
        materials: ['textile', 'metal'],
        date: 1959,
      },
      {
        productId: '6',
        thumbSrc: '/media/archive/verner_panton/products/6/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Living Tower',
        categories: ['sofa'],
        materials: ['textile'],
        date: 1969,
      },
      {
        productId: '7',
        thumbSrc: '/media/archive/verner_panton/products/7/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Panton',
        categories: ['chairs'],
        materials: ['plastic'],
        date: 1960,
      },
      {
        productId: '8',
        thumbSrc: '/media/archive/verner_panton/products/8/thumb.png',
        story: [],
        nickname: null,
        brand: null,
        productURL: null,
        dimensionsCm: null,
        model: 'Peacock',
        categories: ['chairs'],
        materials: ['textile', 'metal'],
        date: 1960,
      },
    ],
    quote: null,
  },
];

export default designers;
