const designers: Designer[] = [
  {
    firstName: 'Aksel',
    lastName: 'Bender-Madsen',
    id: 'aksel-bender-madsen',
    birth: 1916,
    death: 2000,
    thumbSrc: 'media/archive/avatars/img1.jpg',
    bio: [],
    works: [
      {
        id: 'product1',
        thumbSrc: 'media/archive/productThumbs/product1.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Metropolitan',
        tags: ['seating'],
        date: 1950,
      },
      {
        id: 'product2',
        thumbSrc: 'media/archive/productThumbs/product2.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1955,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Arne',
    lastName: 'Jacobsen',
    id: 'arne-jacobsen',
    thumbSrc: 'media/archive/avatars/img2.jpg',

    birth: 1902,
    death: 1971,
    quote: 'The primary factor is... proportions.',
    bio: [
      'One of Denmark‘s most respected architects, Arne Jacobsen (1902-1971), has become synonymous with modernism internationally. His furniture designs, most created in connection with specific architectural projects, continue to excite both in Denmark and abroad.',
      'Jacobsen viewed himself primarily as an architect. His functionalist buildings span from small holiday homes to large hospitality projects, with all details designed by Jacobsen himself, down to cutlery and door handles. One of his best-known projects is the SAS Royal Hotel in Copenhagen – he was the architect, and designed all the interior elements.',
      'While architecture was Jacobsen’s primary focus, he also worked with lighting, textiles, furniture and industrial design, approaching all projects with the same perfectionism that defined his career. Striving for a balance of organic simplicity and functionalism, he considered every detail, and was inspired by nature, whose organic shapes informed several of his furniture pieces. Jacobsen’s love of flowers and landscape gardening is also seen in his watercolors, wallpapers and fabrics. Jacobsen initially trained as a mason and, after graduating from a technical college in Copenhagen in 1924, began his studies as an architect at the Royal Danish Academy of Fine Arts. Here he was influenced by lecturers and leading designers such as Kaare Klint and Kay Fisker, known for their rigorous design approach.',
      'Jacobsen also taught as a professor at the Royal Academy of Fine Arts in Copenhagen.',
      'He was awarded Honorary Doctorates from the University of Oxford and the University of Strathclyde in Glasgow, and was a member of many European academy councils. He received multiple Danish and international awards, including the RIBA Bronze Medal in 1963 and the Medaille d‘Or from the Académie d‘Architecture de France in 1971.',
    ],
    works: [
      {
        id: 'product3',
        thumbSrc: 'media/archive/productThumbs/product3.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Ant',
        tags: ['seating'],
        date: 1952,
      },
      {
        id: 'product4',
        thumbSrc: 'media/archive/productThumbs/product4.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Egg',
        tags: ['seating'],
        date: 1958,
      },
      {
        id: 'product5',
        thumbSrc: 'media/archive/productThumbs/product5.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Oksen',
        tags: ['seating'],
        date: 1954,
      },
      {
        id: 'product6',
        thumbSrc: 'media/archive/productThumbs/product6.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Oxford',
        tags: ['seating'],
        date: 1952,
      },
      {
        id: 'product7',
        thumbSrc: 'media/archive/productThumbs/product7.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Series 7',
        tags: ['seating'],
        date: 1958,
      },
      {
        id: 'product8',
        thumbSrc: 'media/archive/productThumbs/product8.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Series 3300',
        tags: ['seating'],
        date: 1951,
      },
      {
        id: 'product9',
        thumbSrc: 'media/archive/productThumbs/product9.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Super-Elliptical',
        tags: ['tables'],
        date: 1956,
      },
      {
        id: 'product10',
        thumbSrc: 'media/archive/productThumbs/product10.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Swan',
        tags: ['seating'],
        date: 1958,
      },
    ],
  },
  {
    firstName: 'Arne',
    lastName: 'Vodder',
    id: 'arne-vodder',
    birth: 1926,
    death: 2009,
    thumbSrc: 'media/archive/avatars/img3.jpg',
    bio: [],
    works: [
      {
        id: 'product11',
        thumbSrc: 'media/archive/productThumbs/product11.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['tables'],
        date: 1960,
      },
      {
        id: 'product12',
        thumbSrc: 'media/archive/productThumbs/product12.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Number 62',
        tags: ['seating'],
        date: 1955,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Bernt',
    lastName: 'Petersen',
    id: 'bernt-petersen',
    birth: 1937,
    death: 2017,
    thumbSrc: 'media/archive/avatars/img4.jpg',
    bio: [],
    works: [
      {
        id: 'product13',
        thumbSrc: 'media/archive/productThumbs/product13.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1959,
      },
      {
        id: 'product14',
        thumbSrc: 'media/archive/productThumbs/product14.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Rag Chair',
        tags: ['seating'],
        date: 1955,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Bodil',
    lastName: 'Kjær',
    id: 'bodil-kjær',
    birth: 1932,
    death: null,
    thumbSrc: 'media/archive/avatars/img5.jpg',
    bio: [],
    works: [
      {
        id: 'product15',
        thumbSrc: 'media/archive/productThumbs/product15.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Executive Desk',
        tags: ['tables'],
        date: 1961,
      },
      {
        id: 'product16',
        thumbSrc: 'media/archive/productThumbs/product16.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Executive Drawer Unit',
        tags: ['storage'],
        date: 1961,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Børge',
    lastName: 'Mogensen',
    id: 'børge-mogensen',
    birth: 1914,
    death: 1972,
    thumbSrc: 'media/archive/avatars/img6.jpg',
    bio: [],
    works: [
      {
        id: 'product17',
        thumbSrc: 'media/archive/productThumbs/product17.png',
        story: [],
        nickname: 'Huntsman Chair',
        brand: null,
        model: 'BM1106',
        tags: ['seating'],
        date: 1955,
      },
      {
        id: 'product18',
        thumbSrc: 'media/archive/productThumbs/product18.png',
        story: [],
        nickname: 'Hunting Table',
        brand: null,
        model: 'BM1160',
        tags: ['tables'],
        date: 1955,
      },
      {
        id: 'product19',
        thumbSrc: 'media/archive/productThumbs/product19.png',
        story: [],
        nickname: 'Coupé Sofa',
        brand: null,
        model: 'Model 2292',
        tags: ['seating'],
        date: 1951,
      },
      {
        id: 'product20',
        thumbSrc: 'media/archive/productThumbs/product20.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Model 3171',
        tags: ['seating'],
        date: 1952,
      },
      {
        id: 'product21',
        thumbSrc: 'media/archive/productThumbs/product21.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Model J39',
        tags: ['seating'],
        date: 1956,
      },
      {
        id: 'product22',
        thumbSrc: 'media/archive/productThumbs/product22.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Spanish Chair',
        tags: ['seating'],
        date: 1956,
      },
      {
        id: 'product23',
        thumbSrc: 'media/archive/productThumbs/product23.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Spoke-Back Sofa',
        tags: ['seating'],
        date: 1952,
      },
      {
        id: 'product24',
        thumbSrc: 'media/archive/productThumbs/product24.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Wing Chair',
        tags: ['seating'],
        date: 1954,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Edvard',
    lastName: 'Kindt-Larsen',
    id: 'edvard-kindt-larsen',
    birth: 1901,
    death: 1982,
    thumbSrc: 'media/archive/avatars/img7.jpg',
    bio: [],
    works: [
      {
        id: 'product25',
        thumbSrc: 'media/archive/productThumbs/product25.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1957,
      },
      {
        id: 'product26',
        thumbSrc: 'media/archive/productThumbs/product26.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        date: 1957,
        tags: [],
      },
    ],
    quote: null,
  },
  {
    firstName: 'Ejner',
    lastName: 'Larsen',
    id: 'ejner-larsen',
    birth: 1917,
    death: 1987,
    thumbSrc: 'media/archive/avatars/img8.jpg',
    bio: [],
    works: [
      {
        id: 'product27',
        thumbSrc: 'media/archive/productThumbs/product27.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1961,
      },
      {
        id: 'product28',
        thumbSrc: 'media/archive/productThumbs/product28.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1964,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Erik',
    lastName: 'Ole Jørgensen',
    id: 'erik-ole-jørgensen',
    birth: 1925,
    death: 2002,
    thumbSrc: 'media/archive/avatars/img9.jpg',
    bio: [],
    works: [
      {
        id: 'product29',
        thumbSrc: 'media/archive/productThumbs/product29.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Model J361',
        tags: ['seating'],
        date: 1960,
      },
      {
        id: 'product30',
        thumbSrc: 'media/archive/productThumbs/product30.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Finn',
    lastName: 'Juhl',
    id: 'finn-juhl',
    birth: 1912,
    death: 1989,
    thumbSrc: 'media/archive/avatars/img10.jpg',
    bio: [],
    works: [
      {
        id: 'product31',
        thumbSrc: 'media/archive/productThumbs/product31.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Chieftain Chair',
        tags: ['seating'],
        date: 1949,
      },
      {
        id: 'product32',
        thumbSrc: 'media/archive/productThumbs/product32.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Grasshopper Chair',
        tags: ['seating'],
        date: 1938,
      },
      {
        id: 'product33',
        thumbSrc: 'media/archive/productThumbs/product33.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Model 46',
        tags: ['seating'],
        date: 1946,
      },
      {
        id: 'product34',
        thumbSrc: 'media/archive/productThumbs/product34.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1953,
      },
      {
        id: 'product35',
        thumbSrc: 'media/archive/productThumbs/product35.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['storage'],
        date: 1953,
      },
      {
        id: 'product36',
        thumbSrc: 'media/archive/productThumbs/product36.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['tables'],
        date: 1953,
      },
      {
        id: 'product37',
        thumbSrc: 'media/archive/productThumbs/product37.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Panel System',
        tags: ['storage'],
        date: 1949,
      },
      {
        id: 'product38',
        thumbSrc: 'media/archive/productThumbs/product38.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Pelican Chair',
        tags: ['seating'],
        date: 1940,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Frits',
    lastName: 'Henningsen',
    id: 'frits-henningsen',
    birth: 1889,
    death: 1965,
    thumbSrc: 'media/archive/avatars/img11.jpg',
    bio: [],
    works: [
      {
        id: 'product39',
        thumbSrc: 'media/archive/productThumbs/product39.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1960,
      },
      {
        id: 'product40',
        thumbSrc: 'media/archive/productThumbs/product40.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['storage'],
        date: 1950,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Grete',
    lastName: 'Jalk',
    id: 'grete-jalk',
    birth: 1920,
    death: 2006,
    thumbSrc: 'media/archive/avatars/img12.jpg',
    bio: [],
    works: [
      {
        id: 'product41',
        thumbSrc: 'media/archive/productThumbs/product41.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'GJ 118',
        date: 1958,
        tags: [],
      },
      {
        id: 'product42',
        thumbSrc: 'media/archive/productThumbs/product42.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'GJ Bow',
        date: 1963,
        tags: [],
      },
    ],
    quote: null,
  },
  {
    firstName: 'Hans',
    lastName: 'Bølling',
    id: 'hans-bølling',
    birth: 1931,
    death: null,
    thumbSrc: 'media/archive/avatars/img13.jpg',
    bio: [],
    works: [
      {
        id: 'product43',
        thumbSrc: 'media/archive/productThumbs/product43.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Duck & Duckling',
        tags: ['accessories'],
        date: 1959,
      },
      {
        id: 'product44',
        thumbSrc: 'media/archive/productThumbs/product44.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Mermaid',
        tags: ['accessories'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Hans',
    lastName: 'Olsen',
    id: 'hans-olsen',
    birth: 1919,
    death: 1992,
    thumbSrc: 'media/archive/avatars/img14.jpg',
    bio: [],
    works: [
      {
        id: 'product45',
        thumbSrc: 'media/archive/productThumbs/product45.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Bikini Chair',
        tags: ['seating'],
        date: 1960,
      },
      {
        id: 'product46',
        thumbSrc: 'media/archive/productThumbs/product46.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1955,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Hans',
    lastName: 'Wegner',
    id: 'hans-wegner',
    thumbSrc: 'media/archive/avatars/img15.jpg',
    birth: 1914,
    death: 2007,
    quote: 'If only you could design just one good chair in your life — but, you simply cannot.',
    bio: [
      'Among Danish furniture designers, Hans J. Wegner (1914-2007) is considered one of the most creative, innovative and prolific. Often referred to as the master of the chair, Wegner created almost 500 in his lifetime – many of them considered masterpieces. His iconic Wishbone Chair is probably the most well-known and has been in continuous production since 1950.',
      'Wegner was part of the spectacular generation that created what is today referred to as “the Golden Age” of modern Danish design. “Many foreigners have asked me how we created the Danish style,” Wegner once said. “And I’ve answered that it was a continuous process of purification and of simplification – to cut down to the simplest possible design of four legs, a seat, and a combined back and armrest.”',
      'The son of a cobbler, Wegner was born in 1914 in Tønder, a town in southern Denmark. He began his apprenticeship with Danish master cabinetmaker H. F. Stahlberg when he was just 14 years old. Later on, he moved to Copenhagen and attended the School of Arts and Crafts from 1936 to 1938 before setting out as a furniture designer.',
      'In 1938, Wegner was approached by architects and designers Arne Jacobsen and Erik Møller, and started designing furniture for the new Aarhus City Hall. During the same period, Wegner began collaborating with master cabinetmaker Johannes Hansen, who was a driving force in bringing new furniture design to the Danish public at the Copenhagen Cabinetmakers’ Guild Exhibitions.',
      'The core of Wegner’s legacy is his focus on showing the inner soul of furniture pieces through a simple and functional exterior. Wegner’s background as a cabinetmaker gave him a deep understanding of how to integrate exacting joinery techniques with exquisite form. His aesthetic was also based on a deep respect for wood and its characteristics, and a vast curiosity about other natural materials that enabled him to bring an organic, natural softness to formalistic minimalism.',
      'Wegner established his own design studio in 1943 and created a series of lightweight chairs for Carl Hansen & Søn from 1949 until 1968, including the Wishbone Chair, which has been in production at Carl Hansen & Søn ever since.',
      'Wegner is seen as one of the most renowned and creative Danish furniture designers. He received many design awards, including the Lunning Prize in 1951, the Grand Prix of the Milan Triennale in 1951, the Royal Danish Academy of Fine Arts’ Eckersberg Medal in 1956, Sweden’s Prince Eugen Medal in 1961, the Danish Furniture Prize in 1980, the C. F. Hansen Medal in 1982, and the 8th International Design Award in 1997. He was made an Honorary Royal Designer for industry by the Royal Society of Arts in London in 1959, became an honorary member of the Royal Danish Academy of Fine Arts in 1995, and was awarded an honorary Doctorate by the Royal College of Art in 1997.',
      'Almost all of the world’s major design museums, from the Museum of Modern Art in New York and Designmuseum Danmark in Copenhagen to Die Neue Sammlung in Munich, exhibit his works. Hans J. Wegner died in Denmark in January 2007, aged 92.',
    ],
    works: [
      {
        id: 'product47',
        thumbSrc: 'media/archive/productThumbs/product47.png',
        story: [
          'With a form that is uniquely its own, the iconic CH24 Wishbone Chair by Hans J. Wegner holds a special place in the world of modern design.',
          'When designing the CH24, Wegner chose to combine the back and armrest into a single piece. To give stability to the steam-bent top and ensure comfortable support, Wegner developed the characteristic Y-shaped back that the Wishbone Chair is named after.',
          'More than 100 steps are required to manufacture each Wishbone Chair, most of which are carried out by hand. The hand-woven seat alone takes a skilled craftsman about an hour to create, using approximately 120 meters of paper cord, the impressive durability and stability of which makes the chair both strong and long-lasting. The Wishbone Chair offers comfort and stability as well as satisfying aesthetic desires for distinctive, elegant form.',
          'Over time, the Wishbone Chair has gained recognition as the ideal chair, capturing the essence of modern Danish design.',
        ],
        nickname: 'Wishbone Chair',
        brand: null,
        model: 'CH24',
        tags: ['seating'],
        date: 1949,
      },
      {
        id: 'product48',
        thumbSrc: 'media/archive/productThumbs/product48.png',
        story: [],
        nickname: 'Chinese Chair',
        brand: null,
        model: 'pp56',
        tags: ['seating'],
        date: 1952,
      },
      {
        id: 'product49',
        thumbSrc: 'media/archive/productThumbs/product49.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'pp112',
        tags: ['seating'],
        date: 1978,
      },
      {
        id: 'product50',
        thumbSrc: 'media/archive/productThumbs/product50.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'pp201',
        tags: ['seating'],
        date: 1952,
      },
      {
        id: 'product51',
        thumbSrc: 'media/archive/productThumbs/product51.png',
        story: [
          '“The Round One” as Wegner referred to it with his usual modesty, is one of the most famous Danish pieces of furniture – certainly the most distinctly Danish. In its own modest and simple way it sums up the very essence of traditional Danish woodworking and design philosophy. And it is absolutely the most important work of Hans J. Wegner.',
          'With this chair Wegner came into his own right, no longer needing the inspiration from other cultures and designers that had influenced his earlier works. This chair was created in a language of shape and construction that only Wegner spoke and it triggered the first ever, foreign report on Danish design in the American Interiors Magazine. It also became the cornerstone in a wide range of designs, which for more than a decade constituted the core business of several Danish furniture manufacturers, effectively becoming the main force in the great international breakthrough of Danish Modern.',
          'When John F. Kennedy and Richard Nixon met in the first ever, televised election debate in 1960, they sat in the Round Chair. It was chosen mainly for its comfort and genuine quality - made in Denmark and shipped to the USA to play an important role in this historic event. Eventually the Americans came up with a new and more telling name for this chair. They called it “The Chair”.',
        ],
        nickname: 'Chair',
        brand: null,
        model: 'pp501',
        tags: ['seating'],
        date: 1949,
      },
      {
        id: 'product52',
        thumbSrc: 'media/archive/productThumbs/product52.png',
        story: [],
        nickname: 'Cow Horn Chair',
        brand: null,
        model: 'pp505',
        tags: ['seating'],
        date: 1952,
      },
      {
        id: 'product53',
        thumbSrc: 'media/archive/productThumbs/product53.png',
        story: [],
        nickname: 'Bull Chair',
        brand: null,
        model: 'pp518',
        tags: ['seating'],
        date: 1952,
      },
      {
        id: 'product54',
        thumbSrc: 'media/archive/productThumbs/product54.png',
        story: [
          'When Finn Juhl first saw this chair, he immediately noticed its characteristic back and named it the Peacock Chair - a name that stuck with the chair.',
          'Despite the chair’s almost postmodern design, it was actually designed back in 1947. However, its deliberately modern lines are not merely a question of looks. Rather, the sweeping back with its extravagantly shaped sticks is the mark of ergonomic aesthetics. The stick’s flat part, which gives the chair its peacock-like appearance, is located exactly where the shoulder blades rest against the chair’s back.',
          'The Peacock Chair is historically anchored in the classic British Windsor Chair. As were the case with many of his early works, Wegner updated his sources of inspiration to a modern version while adding sophisticated details that required the greatest accuracy from highly skilled craftsmen.',
        ],
        nickname: 'Peacock Chair',
        brand: null,
        model: 'pp550',
        tags: ['seating'],
        date: 1947,
      },
    ],
  },
  {
    firstName: 'Helge',
    lastName: 'Jensen',
    id: 'helge-jensen',
    birth: 1917,
    death: 1987,
    thumbSrc: 'media/archive/avatars/img16.jpg',
    bio: [],
    works: [
      {
        id: 'product55',
        thumbSrc: 'media/archive/productThumbs/product55.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1955,
      },
      {
        id: 'product56',
        thumbSrc: 'media/archive/productThumbs/product56.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Racket Chair',
        tags: ['seating'],
        date: 1955,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Ib',
    lastName: 'Kofod-Larsen',
    id: 'ib-kofod-larsen',
    birth: 1916,
    death: 2016,
    thumbSrc: 'media/archive/avatars/img17.jpg',
    bio: [],
    works: [
      {
        id: 'product57',
        thumbSrc: 'media/archive/productThumbs/product57.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Seal Chair',
        tags: ['seating'],
        date: 1950,
      },
      {
        id: 'product58',
        thumbSrc: 'media/archive/productThumbs/product58.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Shell Chair',
        tags: ['seating'],
        date: 1950,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Jacob',
    lastName: 'Kjær',
    id: 'jacob-kjær',
    birth: 1896,
    death: 1957,
    thumbSrc: 'media/archive/avatars/img18.jpg',
    bio: [],
    works: [
      {
        id: 'product59',
        thumbSrc: 'media/archive/productThumbs/product59.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'FN Chair',
        tags: ['seating'],
        date: 1958,
      },
      {
        id: 'product60',
        thumbSrc: 'media/archive/productThumbs/product60.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1957,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Jens',
    lastName: 'Quistgaard',
    id: 'jens-quistgaard',
    birth: 1919,
    death: 2008,
    thumbSrc: 'media/archive/avatars/img19.jpg',
    bio: [],
    works: [
      {
        id: 'product61',
        thumbSrc: 'media/archive/productThumbs/product61.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['accessories'],
        date: 1958,
      },
      {
        id: 'product62',
        thumbSrc: 'media/archive/productThumbs/product62.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Safari Chair',
        tags: ['seating'],
        date: 1965,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Jens',
    lastName: 'Risom',
    id: 'jens-risom',
    birth: 1916,
    death: 2016,
    thumbSrc: 'media/archive/avatars/img20.jpg',
    bio: [],
    works: [
      {
        id: 'product63',
        thumbSrc: 'media/archive/productThumbs/product63.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Model 654W',
        tags: ['seating'],
        date: 1943,
      },
      {
        id: 'product64',
        thumbSrc: 'media/archive/productThumbs/product64.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Model 666C',
        tags: ['seating'],
        date: 1943,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Jørgen',
    lastName: 'Gammelgaard',
    id: 'jørgen-gammelgaard',
    birth: 1938,
    death: 1991,
    thumbSrc: 'media/archive/avatars/img21.jpg',
    bio: [],
    works: [
      {
        id: 'product65',
        thumbSrc: 'media/archive/productThumbs/product65.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Model EJ20',
        tags: ['seating'],
        date: 1968,
      },
      {
        id: 'product66',
        thumbSrc: 'media/archive/productThumbs/product66.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1970,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Jørgen',
    lastName: 'Kastholm',
    id: 'jørgen-kastholm',
    birth: 1931,
    death: 2007,
    thumbSrc: 'media/archive/avatars/img22.jpg',
    bio: [],
    works: [
      {
        id: 'product67',
        thumbSrc: 'media/archive/productThumbs/product67.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Desk',
        tags: ['seating'],
        date: 1956,
      },
      {
        id: 'product68',
        thumbSrc: 'media/archive/productThumbs/product68.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'FK87 Grasshopper',
        tags: ['seating'],
        date: 1968,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Kaare',
    lastName: 'Klint',
    id: 'kaare-klint',
    birth: 1888,
    death: 1954,
    thumbSrc: 'media/archive/avatars/img23.jpg',
    bio: [],
    works: [
      {
        id: 'product69',
        thumbSrc: 'media/archive/productThumbs/product69.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Card Chair',
        tags: ['seating'],
        date: 1934,
      },
      {
        id: 'product70',
        thumbSrc: 'media/archive/productThumbs/product70.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Church Chair',
        tags: ['seating'],
        date: 1936,
      },
      {
        id: 'product71',
        thumbSrc: 'media/archive/productThumbs/product71.png',
        story: [],
        nickname: 'Propeller Stool',
        brand: null,
        model: 'KK87830',
        tags: ['seating'],
        date: 1930,
      },
      {
        id: 'product72',
        thumbSrc: 'media/archive/productThumbs/product72.png',
        story: [],
        nickname: 'Faaborg Chair',
        brand: null,
        model: 'KK96620',
        tags: ['seating'],
        date: 1914,
      },
      {
        id: 'product73',
        thumbSrc: 'media/archive/productThumbs/product73.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1933,
      },
      {
        id: 'product74',
        thumbSrc: 'media/archive/productThumbs/product74.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1950,
      },
      {
        id: 'product75',
        thumbSrc: 'media/archive/productThumbs/product75.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Ravenna Chair',
        tags: ['seating'],
        date: 1948,
      },
      {
        id: 'product76',
        thumbSrc: 'media/archive/productThumbs/product76.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Safari Chair',
        tags: ['seating'],
        date: 1933,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Kai',
    lastName: 'Kristiansen',
    id: 'kai-kristiansen',
    birth: 1929,
    death: null,
    thumbSrc: 'media/archive/avatars/img24.jpg',
    bio: [],
    works: [
      {
        id: 'product77',
        thumbSrc: 'media/archive/productThumbs/product77.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Kompass Chair',
        tags: ['seating'],
        date: 1960,
      },
      {
        id: 'product78',
        thumbSrc: 'media/archive/productThumbs/product78.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Model 42',
        tags: ['seating'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Kay',
    lastName: 'Bojesen',
    id: 'kay-bojesen',
    thumbSrc: 'media/archive/avatars/img25.jpg',
    birth: 1886,
    death: 1958,
    quote:
      'An item must function properly, be nice to hold and a pleasure to look at... Above all, it must have a soul.',
    bio: [
      'Silversmith and designer Kay Bojesen had a very special talent. He was able to bring wood to life, and he became world-famous for creating wooden toys that had soul and an impish sense of humour. With more than 2000 pieces to his name, Kay Bojesen was one of Denmark‘s most prolific artisans in the 20th century. He is best known for his playful and cheerful monkeys, royal life guards and other wooden toys, but his wide-ranging production also includes jewellery, cutlery, teapots and silver goblets.',
      'Kay Bojesen graduated as a silversmith in 1910 after completing his apprenticeship with silversmith Georg Jensen. As one of the first Danish artisans to do so, he embraced functionalism. He was among the pioneers who organised Den Permanente association – a cooperative of artists that included a shop and exhibition space which over the decades came to represent the best in Danish and Scandinavian design.1919 became the start of a new era for Kay Bojesen. He got married and his son Otto was born. This sparked Kay Bojesen‘s imagination and fascination for children, toys and wood and brought back memories of his own childhood when his father (the publisher Ernst Bojesen – the publisher of the Danish satirical annual Blæksprutten (The Octopus)) cut wooden figures for him and encouraged his children to be creative, imaginative and playful.',
      'In the 1930s, Kay Bojesen started in earnest to indulge his interest in wood. He created a range of wooden toys that all lived up to his ideal that design should be round, soft and have a good feel to it.',
      'His idea was not to create lifelike copies of real animals or to be too sophisticated or focus too much on detail, but instead to create imaginative toys in designs based on a child‘s own world where ‘lines need to smile’. The wooden toys had to be simple, solid and inspire children to play. With this basic philosophy in mind, Kay Bojesen created his beloved wooden toys that appeal to the child within us all. For generations, Kay Bojesen was seen as the high spirits of Danish industrial design. Today, Kay Bojesen is regarded as one of Denmark‘s biggest designer names and his designs are among the most popular in Danish design.',
      'Kay Bojesen retained his childish curiosity and joie de vivre till the end. Kay Bojesen died at the age of 72 and left an important design heritage behind. A heritage that is now guarded closely by his grandchildren.',
    ],
    works: [
      {
        id: 'product79',
        thumbSrc: 'media/archive/productThumbs/product79.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Bear',
        tags: ['accessories'],
        date: 1952,
      },
      {
        id: 'product80',
        thumbSrc: 'media/archive/productThumbs/product80.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Dog',
        tags: ['accessories'],
        date: 1934,
      },
      {
        id: 'product81',
        thumbSrc: 'media/archive/productThumbs/product81.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Elephant',
        tags: ['accessories'],
        date: 1953,
      },
      {
        id: 'product82',
        thumbSrc: 'media/archive/productThumbs/product82.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Hippo',
        tags: ['accessories'],
        date: 1955,
      },
      {
        id: 'product83',
        thumbSrc: 'media/archive/productThumbs/product83.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Horse',
        tags: ['accessories'],
        date: 1930,
      },
      {
        id: 'product84',
        thumbSrc: 'media/archive/productThumbs/product84.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Monkey',
        tags: ['accessories'],
        date: 1951,
      },
      {
        id: 'product85',
        thumbSrc: 'media/archive/productThumbs/product85.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Pair of Sparrows',
        tags: ['accessories'],
        date: 1950,
      },
      {
        id: 'product86',
        thumbSrc: 'media/archive/productThumbs/product86.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Royal Guardsmen',
        tags: ['accessories'],
        date: 1942,
      },
    ],
  },
  {
    firstName: 'Kurt',
    lastName: 'Østervig',
    id: 'kurt-østervig',
    birth: 1912,
    death: 1986,
    thumbSrc: 'media/archive/avatars/img26.jpg',
    bio: [],
    works: [
      {
        id: 'product87',
        thumbSrc: 'media/archive/productThumbs/product87.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1960,
      },
      {
        id: 'product88',
        thumbSrc: 'media/archive/productThumbs/product88.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['storage'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Mogens',
    lastName: 'Koch',
    id: 'mogens-koch',
    birth: 1914,
    death: 2007,
    thumbSrc: 'media/archive/avatars/img27.jpg',
    bio: [],
    works: [
      {
        id: 'product89',
        thumbSrc: 'media/archive/productThumbs/product89.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Additional Chairs',
        tags: ['seating'],
        date: 1960,
      },
      {
        id: 'product90',
        thumbSrc: 'media/archive/productThumbs/product90.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'MK9920',
        tags: ['seating'],
        date: 1932,
      },
      {
        id: 'product91',
        thumbSrc: 'media/archive/productThumbs/product91.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'MK88360',
        tags: ['storage'],
        date: 1932,
      },
      {
        id: 'product92',
        thumbSrc: 'media/archive/productThumbs/product92.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'MK98400',
        tags: ['storage'],
        date: 1932,
      },
      {
        id: 'product93',
        thumbSrc: 'media/archive/productThumbs/product93.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'MK98860',
        tags: ['tables'],
        date: 1960,
      },
      {
        id: 'product94',
        thumbSrc: 'media/archive/productThumbs/product94.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Model 52',
        tags: ['seating'],
        date: 1936,
      },
      {
        id: 'product95',
        thumbSrc: 'media/archive/productThumbs/product95.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['storage'],
        date: 1960,
      },
      {
        id: 'product96',
        thumbSrc: 'media/archive/productThumbs/product96.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Wingback Chair',
        tags: ['seating'],
        date: 1930,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Mogens',
    lastName: 'Lassen',
    id: 'mogens-lassen',
    birth: 1901,
    death: 1987,
    thumbSrc: 'media/archive/avatars/img28.jpg',
    bio: [],
    works: [
      {
        id: 'product97',
        thumbSrc: 'media/archive/productThumbs/product97.png',
        story: [],
        nickname: 'Egyptian Table',
        brand: null,
        model: 'ML10097',
        tags: ['tables'],
        date: 1961,
      },
      {
        id: 'product98',
        thumbSrc: 'media/archive/productThumbs/product98.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1961,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Nanna',
    lastName: 'Ditzel',
    id: 'nanna-ditzel',
    birth: 1925,
    death: 2003,
    thumbSrc: 'media/archive/avatars/img29.jpg',
    bio: [],
    works: [
      {
        id: 'product99',
        thumbSrc: 'media/archive/productThumbs/product99.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Hanging Egg',
        tags: ['seating'],
        date: 1959,
      },
      {
        id: 'product100',
        thumbSrc: 'media/archive/productThumbs/product100.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Madame Chair',
        tags: ['seating'],
        date: 1965,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Ole',
    lastName: 'Wanscher',
    id: 'ole-wanscher',
    birth: 1903,
    death: 1985,
    thumbSrc: 'media/archive/avatars/img30.jpg',
    bio: [],
    works: [
      {
        id: 'product101',
        thumbSrc: 'media/archive/productThumbs/product101.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Colonial Armchair',
        tags: ['seating'],
        date: 1949,
      },
      {
        id: 'product102',
        thumbSrc: 'media/archive/productThumbs/product102.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Colonial Sofa',
        tags: ['seating'],
        date: 1964,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Orla',
    lastName: 'Mølgaard-Nielsen',
    id: 'orla-mølgaard-nielsen',
    birth: 1907,
    death: 1993,
    thumbSrc: 'media/archive/avatars/img31.jpg',
    bio: [],
    works: [
      {
        id: 'product103',
        thumbSrc: 'media/archive/productThumbs/product103.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'AX Chair',
        tags: ['seating'],
        date: 1960,
      },
      {
        id: 'product104',
        thumbSrc: 'media/archive/productThumbs/product104.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Peder',
    lastName: 'Moos',
    id: 'peder-moos',
    birth: 1906,
    death: 1991,
    thumbSrc: 'media/archive/avatars/img32.jpg',
    bio: [],
    works: [
      {
        id: 'product105',
        thumbSrc: 'media/archive/productThumbs/product105.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1949,
      },
      {
        id: 'product106',
        thumbSrc: 'media/archive/productThumbs/product106.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['tables'],
        date: 1949,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Peter',
    lastName: 'Hvidt',
    id: 'peter-hvidt',
    birth: 1916,
    death: 1986,
    thumbSrc: 'media/archive/avatars/img33.jpg',
    bio: [],
    works: [
      {
        id: 'product107',
        thumbSrc: 'media/archive/productThumbs/product107.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['storage'],
        date: 1951,
      },
      {
        id: 'product108',
        thumbSrc: 'media/archive/productThumbs/product108.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'X Chair',
        tags: ['seating'],
        date: 1950,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Poul',
    lastName: 'Henningsen',
    id: 'poul-henningsen',
    thumbSrc: 'media/archive/avatars/img34.jpg',
    birth: 1894,
    death: 1967,
    quote: 'The technician should never forget that he is an artist, the artist never that he is a technician.',
    bio: [
      'Poul Henningsen was born in Copenhagen by the famous Danish writer Agnes Henningsen. He never graduated as an architect, but studied at The Technical School at Frederiksberg, Denmark from 1911-14, and then at Technical College in Copenhagen from 1914-17. He started practicing traditional functionalistic architecture, but over the years his professional interests changed to focus mainly on lighting which is what he is most famous for.',
      'He also expanded his field of occupation into areas of writing, becoming a journalist and an author. For a short period at the beginning of WWII, he was the head architect of the Tivoli Gardens in Copenhagen. But like many other creative people, he was forced to flee Denmark during the German occupation but soon became a vital part of the Danish colony of artists living in Sweden.',
      'His lifelong collaboration with Louis Poulsen began in 1925 and lasted until his death. To this day, Louis Poulsen still benefits from his genius. Poul Henningsen was also the first editor of the company magazine “NYT”. The CEO of Louis Poulsen at the time, Sophus Kaastrup-Olsen, gave the magazine to PH as a gift because he had been terminated from the Danish newspaper he worked for (his opinions were too radical).',
      'Poul Henningsen‘s pioneering work concerning the relations between light structures, shadows, glare, and color reproduction—compared to man’s need for light remains the fondation of the lighting theories still practiced by Louis Poulsen.',
    ],
    works: [],
  },
  {
    firstName: 'Poul',
    lastName: 'Kjærholm',
    id: 'poul-kjærholm',
    thumbSrc: 'media/archive/avatars/img35.jpg',
    birth: 1929,
    death: 1980,
    quote:
      'Steel’s constructive potential is not the only thing that interests me; the refraction of light on its surface is an important part of my artistic work. I consider steel a material with the same artistic merit as wood and leather.',
    bio: [
      'Poul Kjærholm combined his strict, modern idiom with an uncompromising approach to quality and materials rooted in Danish craftsmanship traditions. Despite his short career as a furniture designer, Kjærholm’s exquisite craftsmanship and clear expression resulted in timeless designs whose influence extended globally and well beyond his own lifetime.',
      'Kjærholm became known for his modernist steel, leather and glass furniture. After training as a cabinetmaker, he studied furniture design at the Royal Danish Academy of Fine Arts in Copenhagen, graduating in 1952. Kjærholm returned as a lecturer in 1955, succeeding Ole Wanscher as professor in 1976. He remained at the Academy until his death in 1980, influencing through his work and teaching both within and outside the Academy.',
      'Just like Kaare Klint, Kjærholm removed unnecessary ornamentation in favor of clarity and function – the hallmarks in his work as both an educator and a designer. He avoided easy solutions and fads in his search for each material’s own language. Kjærholm’s linear aesthetic and expression were influenced by global pioneers such as Gerrit Rietveld, Mies van der Rohe and Charles and Ray Eames.',
      'In the post-war years, Kjærholm distanced himself from the rounded, organic shapes of contemporary Danish design. As industrialization took off, Kjærholm felt that Denmark could only industrialize production if its products were technically superior to their traditionally crafted counterparts – he sought new ways to unite tradition and innovation. Kjærholm‘s furniture is represented in many international museums, including the Museum of Modern Art in New York. His awards include the Lunning Award in 1958, the Eckersberg Medal in 1960, and multiple ID Prizes.',
    ],
    works: [
      {
        id: 'product109',
        thumbSrc: 'media/archive/productThumbs/product109.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'PK1',
        tags: ['seating'],
        date: 1955,
      },
      {
        id: 'product110',
        thumbSrc: 'media/archive/productThumbs/product110.png',
        story: [
          'The discrete and elegant lounge chair PK22 epitomizes the work of Poul Kjærholm and his search for the ideal form and industrial dimension, which was always present in his designs. The PK22 was an immediate commercial and critical success. In 1957, the chair was awarded the Grand Prix at the Milan Triennale, the world’s premier design fair. The prize catapulted Kjærholm’s career to the highest level and immediately he became a name on the international scene, a position he has enjoyed ever since.',
          'The profile of the steel frame structure on PK22 originates from Poul Kjærholm‘s graduation project, the “Element” chair (today known as PK25), from the School of Applied Arts in Copenhagen. The frame for PK25 was designed from a single piece of steel, but for PK22 the steel structure was divided into separate elements due to design improvements and for more economical production.',
          'The PK22 is made from one seat and back piece mounted on the steel frame. The seat and back piece are available in canvas, suede and leather as well as in wicker. The frame is made of satin brushed stainless spring steel.',
        ],
        nickname: null,
        brand: null,
        model: 'PK22',
        tags: ['seating'],
        date: 1956,
      },
      {
        id: 'product111',
        thumbSrc: 'media/archive/productThumbs/product111.png',
        story: [
          'The PK24 chaise longue chair, with its easy curves and organic shape, stands out as perhaps the most recognizable chair in Poul Kjærholm’s work. Inspiration for this chair comes from the Rococo period and the French chaise longue – “long chair” – that featured the same curve and size. The chair is a prime and almost extreme example of Kjærholm’s principle of designing with independent elements. Consequently, the chair has no physical connection between the main parts, which are instead kept together by gravity and the friction between the elements. Kjærholm also labelled the PK24 the “Hammock Chair” to stress that the chair functioned by suspending the body between two points.',
          'The PK24 chaise longue is available in wicker and leather, both versions include a leather headrest. The seat and back are curved on a steel frame covered with handwoven wicker or leather – they glide on the frame thus adjusting to the desired position. The head cushion - covered in leather and with a counterweight of stainless steel - is adjustable, optimizing the comfort and rest. The frame is made of satin brushed stainless spring steel.',
        ],
        nickname: 'Hammock Chair',
        brand: null,
        model: 'PK24',
        tags: ['seating'],
        date: 1965,
      },
      {
        id: 'product112',
        thumbSrc: 'media/archive/productThumbs/product112.png',
        story: [
          'The PK25 was designed by Poul Kjærholm in 1951, for his final graduation project at the School of Applied Arts in Copenhagen. The PK25, also known as the “Element” chair, is a fine example of the young Kjærholm’s eagerness to work with common, industrial materials. Kjærholm was determined to reduce the chair to a single piece of each material, resulting in the overarching hallmark of the chair: the continuous and rather complex steel frame that is bent from a single piece without joints and connections.',
          'The frame of the PK25 lounge chair is made from a single piece of matt chromed spring steel. A long length of flag halyard wound around the seat and back of the curved steel frame forms in simplicity the chair. The flag halyard is made from line with a nylon core.',
        ],
        nickname: 'Element Chair',
        brand: null,
        model: 'PK25',
        tags: ['seating'],
        date: 1951,
      },
      {
        id: 'product113',
        thumbSrc: 'media/archive/productThumbs/product113.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'PK31',
        tags: ['seating'],
        date: 1960,
      },
      {
        id: 'product114',
        thumbSrc: 'media/archive/productThumbs/product114.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'PK52',
        tags: ['tables'],
        date: 1955,
      },
      {
        id: 'product115',
        thumbSrc: 'media/archive/productThumbs/product115.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'PK58',
        tags: ['tables'],
        date: 1960,
      },
      {
        id: 'product116',
        thumbSrc: 'media/archive/productThumbs/product116.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'PK80',
        tags: ['seating'],
        date: 1957,
      },
    ],
  },
  {
    firstName: 'Poul',
    lastName: 'Volther',
    id: 'poul-volther',
    birth: 1923,
    death: 2001,
    thumbSrc: 'media/archive/avatars/img36.jpg',
    bio: [],
    works: [
      {
        id: 'product117',
        thumbSrc: 'media/archive/productThumbs/product117.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'EJ 5 Corona',
        tags: ['seating'],
        date: 1961,
      },
      {
        id: 'product118',
        thumbSrc: 'media/archive/productThumbs/product118.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'EJ 5-F',
        tags: ['seating'],
        date: 1961,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Preben',
    lastName: 'Fabricius',
    id: 'preben-fabricius',
    birth: 1931,
    death: 1984,
    thumbSrc: 'media/archive/avatars/img37.jpg',
    bio: [],
    works: [
      {
        id: 'product119',
        thumbSrc: 'media/archive/productThumbs/product119.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Model 710',
        tags: ['seating'],
        date: 1959,
      },
      {
        id: 'product120',
        thumbSrc: 'media/archive/productThumbs/product120.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Tulip',
        tags: ['seating'],
        date: 1961,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Rigmor',
    lastName: 'Andersen',
    id: 'rigmor-andersen',
    birth: 1903,
    death: 1995,
    thumbSrc: 'media/archive/avatars/img38.jpg',
    bio: [],
    works: [
      {
        id: 'product121',
        thumbSrc: 'media/archive/productThumbs/product121.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['seating'],
        date: 1960,
      },
      {
        id: 'product122',
        thumbSrc: 'media/archive/productThumbs/product122.png',
        story: [],
        nickname: null,
        brand: null,
        model: null,
        tags: ['tables'],
        date: 1960,
      },
    ],
    quote: null,
  },
  {
    firstName: 'Verner',
    lastName: 'Panton',
    id: 'verner-panton',
    birth: 1926,
    death: 1998,
    thumbSrc: 'media/archive/avatars/img39.jpg',
    bio: [],
    works: [
      {
        id: 'product123',
        thumbSrc: 'media/archive/productThumbs/product123.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Amoebe',
        tags: ['seating'],
        date: 1970,
      },
      {
        id: 'product124',
        thumbSrc: 'media/archive/productThumbs/product124.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Barboy',
        tags: ['accessories'],
        date: 1964,
      },
      {
        id: 'product125',
        thumbSrc: 'media/archive/productThumbs/product125.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'C1',
        tags: ['seating'],
        date: 1964,
      },
      {
        id: 'product126',
        thumbSrc: 'media/archive/productThumbs/product126.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Cone',
        tags: ['seating'],
        date: 1959,
      },
      {
        id: 'product127',
        thumbSrc: 'media/archive/productThumbs/product127.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Heart',
        tags: ['seating'],
        date: 1959,
      },
      {
        id: 'product128',
        thumbSrc: 'media/archive/productThumbs/product128.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Living Tower',
        tags: ['seating'],
        date: 1969,
      },
      {
        id: 'product129',
        thumbSrc: 'media/archive/productThumbs/product129.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Panton',
        tags: ['seating'],
        date: 1960,
      },
      {
        id: 'product130',
        thumbSrc: 'media/archive/productThumbs/product130.png',
        story: [],
        nickname: null,
        brand: null,
        model: 'Peacock',
        tags: ['seating'],
        date: 1960,
      },
    ],
    quote: null,
  },
];

export default designers;
