const craftData: CraftTopic[] = [
  {
    name: 'Wood',
    vidSrc: 'media/craft/wood.mp4',
    type: 'material',
    keywords: [],
    id: 'wood',
  },
  {
    name: 'Leather',
    vidSrc: 'media/craft/leather.mp4',
    type: 'material',
    keywords: [],
    id: 'leather',
  },
  {
    name: 'Metal',
    vidSrc: 'media/craft/metal.mp4',
    type: 'material',
    keywords: [],
    id: 'metal',
  },
  {
    name: 'Papercord',
    vidSrc: 'media/craft/papercord.mp4',
    type: 'material',
    keywords: [],
    id: 'papercord',
  },
  {
    name: 'Textile',
    vidSrc: 'media/craft/textile.mp4',
    type: 'material',
    keywords: [],
    id: 'textile',
  },
  {
    name: 'Steam Bending',
    vidSrc: '',
    type: 'technique',
    id: 'steam-bending',
    keywords: [],
  },
  {
    name: 'Pre-compression',
    vidSrc: '',
    type: 'technique',
    id: 'pre-compression',
    keywords: [],
  },
  {
    name: 'Molding',
    vidSrc: '',
    type: 'technique',
    id: 'molding',
    keywords: [],
  },
  {
    name: 'Templates',
    vidSrc: '',
    type: 'technique',
    id: 'templates',
    keywords: [],
  },
  {
    name: 'Copying Lathe',
    vidSrc: '',
    type: 'technique',
    id: 'copying-lathe',
    keywords: [],
  },
  { name: 'CNC', vidSrc: '', type: 'technique', id: 'cnc', keywords: [] },
];

export default craftData;
